services:
  - type: web
    name: changemee-rebounder
    runtime: static
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
